create sequence seq_appuser start with 1 increment by 1;
create sequence seq_course start with 1 increment by 1;
create sequence seq_material start with 1 increment by 1;
create sequence seq_module start with 1 increment by 1;
create sequence seq_recognition start with 1 increment by 1;
create sequence seq_userhistory start with 1 increment by 1;
create table appuser (enabled_appuser boolean not null, created_at_appuser timestamp(6) with time zone not null, id_appuser bigint not null, email_appuser varchar(64) not null, name_appuser varchar(64) not null, password_appuser varchar(128) not null, primary key (id_appuser), unique (email_appuser));
create table chapter (order_chapter integer not null, admin_chapter bigint not null, course_chapter bigint not null, content_chapter text, description_chapter text, name_chapter varchar(255) not null, primary key (order_chapter, course_chapter));
create table chaptermaterial (order_chaptermaterial integer not null, course_chaptermaterial bigint not null, material_chaptermaterial bigint not null, primary key (order_chaptermaterial, course_chaptermaterial, material_chaptermaterial));
create table course (durationmin_course integer not null, admin_course bigint not null, id_course bigint not null, description_course text, externalurl_course varchar(255), name_course varchar(255) not null, primary key (id_course), unique (name_course));
create table material (type_material smallint not null check (type_material between 0 and 2), id_material bigint not null, description_material varchar(255), name_material varchar(255) not null, url_material varchar(255) not null, primary key (id_material));
create table module (admin_module bigint not null, id_module bigint not null, description_module varchar(255), name_module varchar(255) not null, primary key (id_module), unique (name_module));
create table modulecourse (course_modulecourse bigint not null, module_modulecourse bigint not null, primary key (course_modulecourse, module_modulecourse));
create table recognition (course_recognition bigint not null, createdat_recognition timestamp(6) with time zone not null, id_recognition bigint not null, user_recognition bigint not null, primary key (id_recognition));
create table role (roles_appuser smallint check (roles_appuser between 0 and 1), id_appuser bigint not null);
create table userhistory (order_userhistory integer not null, course_userhistory bigint not null, endtime_userhistory timestamp(6) with time zone, id_userhistory bigint not null, starttime_userhistory timestamp(6) with time zone not null, user_userhistory bigint not null, primary key (id_userhistory), unique (user_userhistory, course_userhistory, order_userhistory));
alter table if exists chapter add constraint FKrdm069nvov2uh9glc6qji2d86 foreign key (course_chapter) references course;
alter table if exists chapter add constraint FKh11t0o6vqetptg093euv9ctio foreign key (admin_chapter) references appuser;
alter table if exists chaptermaterial add constraint FKdaaaegdxppudhwpk8ktugvn4c foreign key (material_chaptermaterial) references material;
alter table if exists chaptermaterial add constraint FKhpfy9m40uibf26toahed7piau foreign key (order_chaptermaterial, course_chaptermaterial) references chapter;
alter table if exists course add constraint FK9x4v64ldbcpgg4iqarmfm9ccu foreign key (admin_course) references appuser;
alter table if exists module add constraint FKr8e5pjr44ek40xud5nv16vd1j foreign key (admin_module) references appuser;
alter table if exists modulecourse add constraint FKdd91f8meu822wkdasns850onx foreign key (course_modulecourse) references course;
alter table if exists modulecourse add constraint FK19idobl95ic4jxja04o51bjfp foreign key (module_modulecourse) references module;
alter table if exists recognition add constraint FK136f0r94xt62ylj6a4bcs7037 foreign key (course_recognition) references course;
alter table if exists recognition add constraint FKfw861l62mnti3udw9isk92ci6 foreign key (user_recognition) references appuser;
alter table if exists role add constraint FKywmt8iorqf792wswtw95bnal foreign key (id_appuser) references appuser;
alter table if exists userhistory add constraint FKbb1k6x2alo5bfg2nx0alx4r6n foreign key (order_userhistory, course_userhistory) references chapter;
alter table if exists userhistory add constraint FK2cqts4mk4qoyodh3fi8w497vl foreign key (user_userhistory) references appuser;
